### ISSUE TITLE
Jails not showing data

### ISSUE THREAD

**Issue by kramttocs** [swissmakers/fail2ban-ui#33]
When clicking the jail name for active blocks or clicking the Edit Filter button from the Manager Jails modal, the Jail Configuration is empty except for the jail definition header: [jail name]

The Filter configuration box is showing content as expected.

**Comment by swissmakers** [comment]
What connector do you use? Local or SSH.
For the local connecter the auto-migration of a single jail.local file to seperate jail.d/jailname.conf should work. (On the SSH Connector there is currently a bug, which i have to fix.)
When then editing a Jail/Filter on the webUI, it should correctly load both. After making changes and hit save, it will store your changes to a .local file (with same name for jails in jail.d and filters in filter.d), to preserve the original file.

**Comment by kramttocs** [comment]
Hey. I am using Local

Repro steps:

In my jail.local I have (among several others):

```
[vikunja]
enabled  = true   
ignoreip = [list of ip ranges here]
backend  = auto      
filter   = vikunja  
#port = 0:65535
logpath  = /remotelogs/vikunja/standard.log
```

I have a vikunja.local filter but there is NO .conf filter ( I may be seeing a pattern of this)

1. Click Manage Jails
2. I see vikunja with the toggle enabled as expected
3. click Edit filter

<img width="1133" height="725" alt="Image" src="https://github.com/user-attachments/assets/acc368d4-e635-4868-9012-fae7e06698c8" />

**Comment by swissmakers** [comment]
Hey. I did a few big changes here in the last days.. Maybe you can try again? I hope it works now for you.
Little hint: When the jail and filter have the same names like [vikunja]  and filter = vikunja, you must not set the filter by your own. Fail2ban should correctly handle that.
Cheers Michael :)

**Comment by swissmakers** [comment]
Should be fixed. If not, please reopen. Cheers

**Comment by kramttocs** [comment]
Hey @swissmakers 
I am still seeing the same though the path in the Filter/Jail popup is nice!

I believe the issue is all about a combined jail.local file in jail.d. 

When I click on a filter/jail, it appears to just be looking for .conf first and then .local and then stops. This isn't unexpected but just not my setup.

<img width="1548" height="981" alt="Image" src="https://github.com/user-attachments/assets/35411891-4e2f-4671-8ea1-fd106ca09aee" />

That shows a jail because a .conf file exists but it's not MY jail. My jail is in my jail.local file:

<img width="528" height="126" alt="Image" src="https://github.com/user-attachments/assets/0e662362-3bc9-45fd-9263-69f3d9003bdc" />

Similarly if there isn't a .conf file at all then it does look for a .local I am guessing based on the path shown here but if that doesn't exist then it's just blank. It never looks at my jail.local?

<img width="1537" height="903" alt="Image" src="https://github.com/user-attachments/assets/c49355c5-f956-4b9d-a27b-a2cb6692b73c" />

**Comment by kramttocs** [comment]
(looks like I don't have access to reopen)

**Comment by kramttocs** [comment]
To be fair - I realize that I am mixing manually configuring fail2ban with what fail2ban-ui is intended to be responsible for.

I am sure if I fully adopted UI as the 'manager' then this wouldn't be an issue. Just haven't made that move yet :)

**Comment by kramttocs** [comment]
Let me say again - this utility is fantastic.

I went ahead and split out my jail.d/jail.local into separate xxxx.local jails and the UI handles it like expected.

So I do think a combine jail is still valid, this issue is no longer really a problem for me.

**Comment by swissmakers** [comment]
Ok i will close this, because it is solved for you, and maybe I will later also implement a pharsing of a whole - unmanaged jail.local, but this can lead to a lot of errors, because of that i went away from that

**Comment by kramttocs** [comment]
Completely understand. It goes against the design of F2B UI so I agree with your call
